version: '3.1'

services:

  db:
    image: postgres:15.1-alpine
    container_name: ${DB_NAME} 
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_NAME}


  # db:
  #   image: mysql:8.0.31
  #   container_name: ${DB_NAME}
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   ports:
  #     - ${DB_PORT}:3306
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_DATABASE: ${DB_NAME}
      # MYSQL_USER: ${DB_USERNAME}
      # MYSQL_PASSWORD: ${DB_PASSWORD}

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080