name: Deploy

on: [push]


jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Despliegue en Droplet de DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /var/www/api-admin.relex-dev.com
            sudo rm -r html
            git clone https://github.com/Rey9530/api_administracion.git html && cd html
            sudo rm -r .git
            yarn install
            npx prisma migrate deploy
            yarn run tsc
            pm2 restart mi-api
            
# export NVM_DIR=~/.nvm
# source ~/.nvm/nvm.sh
# rm -rf test
# mkdir test
# cd test
# git clone git@github.com:username/projectname
# echo 'Deployment to digital ocean finished'

