name: Deploy

on: [push]


jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Despliegue en Droplet de DigitalOcean
        uses: appleboy/ssh-action@master 
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /var/www/api-admin.relex-dev.com/html
            git pull
            sudo rm -r .env 
            echo "Configuran Variables en ENV"  
            sudo echo "JWT_SECRET=${{secrets.JWT_SECRET}}" >> .env
            sudo echo "DB_PASSWORD=${{secrets.DB_PASSWORD}}" >> .env
            sudo echo "DB_NAME=${{secrets.DB_NAME}}" >> .env
            sudo echo "DB_HOST=${{secrets.DB_HOST}}" >> .env
            sudo echo "DB_PORT=${{secrets.DB_PORT}}" >> .env
            sudo echo "CLOUDINARY_CLOUD_NAME=${{secrets.CLOUDINARY_CLOUD_NAME}}" >> .env
            sudo echo "CLOUDINARY_API_KEY=${{secrets.CLOUDINARY_API_KEY}}" >> .env
            sudo echo "CLOUDINARY_API_SECRET=${{secrets.CLOUDINARY_API_SECRET}}" >> .env 
            sudo echo "DATABASE_URL=postgresql://${{secrets.DB_NAME}}:${{secrets.DB_PASSWORD}}@localhost:${{secrets.DB_PORT}}/${{secrets.DB_NAME}}?schema=public" >> .env 
            sudo echo "PORT=${{secrets.PORT_API}}" >> .env 
            echo "Fin Variables en ENV"

            yarn install  
            npx prisma migrate deploy
            yarn run tsc
            pm2 restart mi-api


# sudo rm -r html
# git clone https://github.com/Rey9530/api_administracion.git html && cd html 