name: Deploy

on: [push]


jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Despliegue en Droplet de DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            echo ${{secrets.JWT_SECRET}}
# cd /var/www/api-admin.relex-dev.com
# sudo rm -r html
# git clone https://github.com/Rey9530/api_administracion.git html && cd html 

# yarn install

# sudo rm -r .git
# yarn install
# npx prisma migrate deploy
# yarn run tsc
# pm2 restart mi-api
            



# env:
#   PORT_API=${{secrets.PORT_API}}
#   JWT_SECRET=${{secrets.JWT_SECRET}}
#   DB_PASSWORD=${{secrets.DB_PASSWORD}}
#   DB_NAME=${{secrets.DB_NAME}}
#   DB_HOST=${{secrets.DB_HOST}}
#   DB_PORT=${{secrets.DB_PORT}}
#   CLOUDINARY_CLOUD_NAME=${{secrets.CLOUDINARY_CLOUD_NAME}}
#   CLOUDINARY_API_KEY=${{secrets.CLOUDINARY_API_KEY}}
#   CLOUDINARY_API_SECRET=${{secrets.CLOUDINARY_API_SECRET}} 




# export NVM_DIR=~/.nvm
# source ~/.nvm/nvm.sh
# rm -rf test
# mkdir test
# cd test
# git clone git@github.com:username/projectname
# echo 'Deployment to digital ocean finished'




# echo "Configuran Variables en ENV"  
# sudo echo "PORT=${PORT_API}" >> .env
# sudo echo "JWT_SECRET=${JWT_SECRET}" >> .env
# sudo echo "DB_PASSWORD=${DB_PASSWORD}" >> .env
# sudo echo "DB_NAME=${DB_NAME}" >> .env
# sudo echo "DB_HOST=${DB_HOST}" >> .env
# sudo echo "DB_PORT=${DB_PORT}" >> .env
# sudo echo "CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}" >> .env
# sudo echo "CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}" >> .env
# sudo echo "CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}" >> .env 
# sudo echo "DATABASE_URL=postgresql://${DB_NAME}:${DB_PASSWORD}@localhost:${DB_PORT}/${DB_NAME}?schema=public" >> .env  
# echo "Fin Variables en ENV"